### ISSUE TITLE
Client CSRs not approved

### ISSUE THREAD

**Issue by rimasgo** [adfinis-sygroup/openshift-csr-approver#2]
Hello,

This is a very useful for openshift v4 UPI type installation. However, I found that it only approves server CSRs and not the client ones. 

Client CSRs username starts with system:serviceaccount where Server CSRs username starts with system:node. I have went through the code and line 142 is checking if the CSR username is system:node:* and fails if it's not. 

Is there any plan to add client CSR approval or should I write something of my own?

Thank you!

**Comment by eyenx** [comment]
Hi @rimasgo 

Sorry for the late reply. We mainly used this for autoapproving Node CSR when installing Openshift on bare metal. There is no plan to implement a feature where serviceaccount CSR are approved.

Regards.
